### ISSUE TITLE
Some units listed with Qty.getUnits are unrecognized

### ISSUE THREAD

**Issue by harmanpa** [gentooboontoo/js-quantities#101]
```Qty.getUnits('volume')``` lists a set of units including 'beerbarrel' and 'oilbarrel'.

However ```Qty('beerbarrel')``` results in an unrecognized unit error.

The reason for this appears to be that in definitions.js, the unit is defined as:
```  "<beerbarrel>":  [["bl","bl-us","beer-barrel","beer-barrels"], 0.1173477658, "volume", ["<meter>","<meter>","<meter>"]],```
where 'beerbarrel' is not in the list of aliases.

**Comment by nwesterman** [comment]
Would like to second this. Was attempting to get a list of all known aliases, but it throws an error when iterating over the provided list.
Reproducible with runkit https://npm.runkit.com/js-quantities
```js
var Qty = require("js-quantities")
const allUnits = Qty.getUnits()
const allias = allUnits.map(u => Qty.getAliases(u))
```
Error: 
``` 
QtyErrorProperties 
message: "Unit not recognized"
name: "QtyError"
```

**Comment by bcowgill** [comment]
Was just evaluating version 1.7.5 and still seeing this problem.

volume:
        beerbarrel: Qty(1, beerbarrel) QtyError: Unit not recognized; getAliases(beerbarrel) QtyError: Unit not recognized
        beerbarrel-imp: Qty(1, beerbarrel-imp) QtyError: Unit not recognized; getAliases(beerbarrel-imp) QtyError: Unit not recognized
        oilbarrel: Qty(1, oilbarrel) QtyError: Unit not recognized; getAliases(oilbarrel) QtyError: Unit not recognized

apologies if this is queued for release or something.
