### ISSUE TITLE
incorrect definition of "amu" and "dalton"

### ISSUE THREAD

**Issue by rage-shadowman** [gentooboontoo/js-quantities#27]
See https://github.com/olbrich/ruby-units/commit/ce2e3c733bf28c209b3e5f912421a26fa5a5e662

Apparently they should be: (12 kg/mol)/(12 * (6.02214129e23/mol))

Or at least that's what ruby-units updated them to be in the above referenced commit (assuming I didn't insert a typo).

**Comment by gentooboontoo** [comment]
Ruby-units's definition is incorrect. It should be (**12 g**/mol)/(12 * (6.02214129e23/mol)).
