### ISSUE TITLE
Publish new version to NPM (current v1.5.0)

### ISSUE THREAD

**Issue by tkirda** [gentooboontoo/js-quantities#55]
Can new version be published to NPM?

There are new functions that we would like to use that are not in current (1.5.0) NPM package (e.g. `Qty.getUnits()`). Thanks! Great work!

**Comment by bkoltai** [comment]
:+1:

**Comment by tkirda** [comment]
Any plans to release new version on NPM soon?

**Comment by gentooboontoo** [comment]
I have just published 1.6.0 version.
