### ISSUE TITLE
Provide a way to know the currently running version

### ISSUE THREAD

**Issue by glepretre** [gentooboontoo/js-quantities#56]
This is an enhancement suggestion :wink: 

As I don't always remember all our dependencies versions, 
I like libraries that provide a way to get it, for example:
```
angular.version
Object {full: "1.3.0", major: 1, minor: 3, dot: 0, codeName: "superluminal-nudge"}
```

Then this information can be useful to know if a recent feature or fix is available.

**Comment by gentooboontoo** [comment]
Done. Thanks for the suggestion.
