### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by babeal** [gentooboontoo/js-quantities#59]
Do you have any plans to create TypeScript type definitions for this package?

**Comment by gentooboontoo** [comment]
No, not for the moment, but I am open to any pull request to add them.

**Comment by wcomartin** [comment]
Waiting for my PR to pass on DefinitelyTyped and this Project will have TypeScript Definitions

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9411

**Comment by gentooboontoo** [comment]
Great. I will reference it once merged.

**Comment by wcomartin** [comment]
Its merged.

**Comment by edgarjrg** [comment]
this should be in the `README as well 👍
