### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by hakas** [gentooboontoo/js-quantities#74]
When calling `Qty.Parse('0.11 180°/sec')`, the method never returns (I'm guessing an infinite loop). 
I would expect it to return null.
If I change the number or remove the ° symbol it returns null as expected.

**Comment by spex** [comment]
+1

**Comment by gentooboontoo** [comment]
Fix merged in `master`. Thanks for reporting.

**Comment by tkirda** [comment]
Excellent! Can we get this on NPM?
