### ISSUE TITLE
ES6 module support on 1.6.4 breaks builds without ES6 support/transpiling (bower.json - main needs to be updated)

### ISSUE THREAD

**Issue by cheung31** [gentooboontoo/js-quantities#77]
For those with a `js-quantities` dependency configured to `~1.6.3` this patch release will break builds if transpiling to ES6 is not a part of the build pipeline.

Perhaps v1.6.4 release should be a major release?

**Comment by gentooboontoo** [comment]
Despite the overhaul, it was not expected to break. `build/quantities.js` is intended to remain ES5 compatible. I was unsure about updating patch or minor but I finally chose patch since there was only a fix and no new feature.

I can't check for the moment, which specific part is breaking ?

**Comment by cheung31** [comment]
@gentooboontoo Ah, I see. I am using Bower to manage my `js-quantities` dependency. Looks like you need to update the `main` in `bower.json` to point to `build/quantities.js` as opposed to `src/quantities.js`

**Comment by gentooboontoo** [comment]
Fixed in 86b8b58d8a9ec6f65c15b1e082c21f5bfc4271ac
