### ISSUE TITLE
(No Bug) Missing property _units for quantities with base units

### ISSUE THREAD

**Issue by librilex** [gentooboontoo/js-quantities#81]
All quantities created with base units and without prefixes do not have the property `_units` defined.
Example: `Qty('1 A')._units` is `undefined`, `Qty('1 kg'))._units` as well.

Is this a bug or on purpose?

(tested with v1.6.6)

**Comment by librilex** [comment]
I figured out that _units is only assigned to quantities with non-base units. To call the units from quantities with base units it is sufficient to use the function units().

**Comment by gentooboontoo** [comment]
It is a private property. As you figured out, it is not meant to be called by client code.
