### ISSUE TITLE
v1.7.1 is a breaking change when used with webpack

### ISSUE THREAD

**Issue by zbjornson** [gentooboontoo/js-quantities#91]
v1.7.1 added a `"module"` field to package.json. Webpack will use that preferentially, which means `require("js-quantities")` returns an object like `{default: <what you'd get from requiring v1.7.0>}`.

**Comment by mxtommy** [comment]
I hit this issue too. Importing it into an Angluar project, now getting "Qty.swiftConverter is not a function" whereas before it was working.

**Comment by gentooboontoo** [comment]
Reverted. Sorry for the breakage.
